[tool.poetry]
name = "fastapi-bim-ar"
version = "0.1.0"
description = "BIM"
authors = ["Takacs Balazs"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.2"
uvicorn = "^0.29.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"